version: '2'

services:
  letter-avatars-app:
    build: .
    volumes:
      - ./cache:/letter-avatars
    environment:
      - TEMP_FILE_PATH=/letter-avatars/app-cache
      - UNICORN_SOCKET_PATH=/letter-avatars/unicorn.sock
  letter-avatars-nginx:
    build: ./nginx
    environment:
      - NGINX_CACHE_PATH=/letter-avatars
    volumes:
      - ./cache:/letter-avatars
    ports:
      - "82:80"
