version: '2'

services:
  letter-avatars-app:
    build: .
    volumes:
      - ./cache:/letter-avatars
    environment:
      - TEMP_FILE_PATH=/letter-avatars/app-cache
    expose:
      - "8080"
  letter-avatars-nginx:
    build: ./nginx
    volumes:
      - ./cache:/letter-avatars
    links:
      - letter-avatars-app
    ports:
      - "82:80"
